version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: blahajid
    volumes:
      - ./pg:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U app -d blahajid
      interval: 5s
      retries: 20
    networks:
      - default
  nexus:
    image: ghcr.io/v3nco/blahajidentity:latest
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - default
      - proxy
    labels:
      - traefik.enable=true"
      - traefik.http.routers.example-service.entrypoints=http
      - traefik.http.routers.example-service.rule=Host(`identity.blahaj.engineering`)
      - traefik.http.routers.example-service.middlewares=rate-limit@file
      - traefik.http.services.example-service.loadbalancer.server.port=3000
networks:
  proxy:
    external: true