version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: blahajid
    volumes:
      - ./pg:/var/lib/postgresql/data
    ports:
      - 5435:5432
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U app -d blahajid
      interval: 5s
      retries: 20
    networks:
      - default
  blahajid:
    image: ghcr.io/v3nco/blahajidentity:latest
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - default
      - proxy
    ports:
      - 3925:3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.blahajid.rule=Host(`blahajid.v3nco.dev`)
      - traefik.http.routers.blahajid.entrypoints=https
      - traefik.http.routers.blahajid.tls.certresolver=myresolver
      - traefik.http.routers.blahajid.priority=1
      - traefik.http.routers.blahajid.middlewares=security-headers@file,rate-limit@file
      - traefik.http.services.blahajid.loadbalancer.server.port=3000
networks:
  proxy:
    external: true
